apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-app
spec:
  template:
    metadata:
      annotations:  
        dapr.io/app-id: frontend-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true" 
        dapr.io/metrics-port: "9092"
        autoscaling.knative.dev/min-scale: "{{ .Values.minScale }}"
    spec:
      containerConcurrency: 0
      containers:
        - image: docker.io/salaboy/frontend-43c85b23484769807bf48fb8b263845e@sha256:9cf5211a840ed7c331b9f3fb257af220e859475919e2991c402a02ce9c5e1770
          name: user-container
          livenessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/liveness
              port: 8080